services:
  db:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_DB=dejavu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - db_network
  python:
    environment:
      - PULSE_SERVER=unix:/mnt/wslg/PulseServer # for WSLg REMOVE WHEN NOT USING WSL
    build:
      context: ./docker/python
    volumes:
      - .:/code
      - /dev/bus/usb:/dev/bus/usb 
      - /mnt/wslg/:/mnt/wslg/ # wslg is for audio (WSL ONLY!)
    working_dir: /code  # <---- Set working directory
    devices:
      - /dev/bus/usb:/dev/bus/usb  
    depends_on:
      - db
    networks:
      - db_network
    ulimits:
      memlock: -1
      rtprio: 99
    #privileged: true
networks:
  db_network:
