services:
  db:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_DB=dejavu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - db_network
  python:
    build:
      context: ./docker/python
    volumes:
      - .:/code
     # - /dev:/dev  # 👈 Mount host device director
    working_dir: /code  # <---- Set working directory
    #devices:
      #- /dev/bus/usb:/dev/bus/usb # <--- Grant usb access??????? We want to do SPECIFICALLY rtlsdr
    #privileged: true # Also added by me
    depends_on:
      - db
    networks:
      - db_network
networks:
  db_network:
