# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHeaderView,
    QLabel, QMainWindow, QPushButton, QSizePolicy,
    QTableView, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame_background = QFrame(self.centralwidget)
        self.frame_background.setObjectName(u"frame_background")
        self.frame_background.setGeometry(QRect(0, 0, 800, 480))
        palette = QPalette()
        brush = QBrush(QColor(210, 196, 158, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
        self.frame_background.setPalette(palette)
        self.frame_background.setAutoFillBackground(False)
        self.frame_background.setStyleSheet(u"background-color: rgb(210, 196, 158);")
        self.frame_background.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_background.setFrameShadow(QFrame.Shadow.Raised)
        self.filters_frame = QFrame(self.frame_background)
        self.filters_frame.setObjectName(u"filters_frame")
        self.filters_frame.setGeometry(QRect(10, 50, 780, 41))
        self.filters_frame.setStyleSheet(u"background-color: rgb(203, 222, 211);\n"
"border-color: rgb(79, 79, 79);")
        self.filters_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.filters_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.filters_frame.setLineWidth(1)
        self.filters_frame.setMidLineWidth(1)
        self.genre_lbl = QLabel(self.filters_frame)
        self.genre_lbl.setObjectName(u"genre_lbl")
        self.genre_lbl.setGeometry(QRect(20, 8, 60, 25))
        palette1 = QPalette()
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush1)
        brush2 = QBrush(QColor(203, 222, 211, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush2)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush2)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush2)
        brush3 = QBrush(QColor(0, 0, 0, 128))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush3)
#endif
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush2)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush2)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush3)
#endif
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush2)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush2)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush2)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush3)
#endif
        self.genre_lbl.setPalette(palette1)
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.genre_lbl.setFont(font)
        self.genre_lbl.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.year_lbl_1 = QLabel(self.filters_frame)
        self.year_lbl_1.setObjectName(u"year_lbl_1")
        self.year_lbl_1.setGeometry(QRect(275, 8, 40, 25))
        palette2 = QPalette()
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush2)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush2)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush2)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush2)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush2)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush2)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush2)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush2)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush2)
        self.year_lbl_1.setPalette(palette2)
        self.year_lbl_1.setFont(font)
        self.genre_cmb = QComboBox(self.filters_frame)
        self.genre_cmb.addItem("")
        self.genre_cmb.addItem("")
        self.genre_cmb.addItem("")
        self.genre_cmb.addItem("")
        self.genre_cmb.addItem("")
        self.genre_cmb.setObjectName(u"genre_cmb")
        self.genre_cmb.setGeometry(QRect(80, 8, 120, 25))
        self.genre_cmb.setStyleSheet(u"background-color: rgb(226, 223, 218);\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Segoe UI\";")
        self.year_cmb_1 = QComboBox(self.filters_frame)
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.addItem("")
        self.year_cmb_1.setObjectName(u"year_cmb_1")
        self.year_cmb_1.setGeometry(QRect(320, 8, 70, 25))
        self.year_cmb_1.setStyleSheet(u"background-color: rgb(226, 223, 218);\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Segoe UI\";")
        self.year_lbl_2 = QLabel(self.filters_frame)
        self.year_lbl_2.setObjectName(u"year_lbl_2")
        self.year_lbl_2.setGeometry(QRect(400, 8, 20, 25))
        palette3 = QPalette()
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush1)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush2)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush2)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush2)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush1)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush2)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush1)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush2)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush2)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush2)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush2)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush2)
        self.year_lbl_2.setPalette(palette3)
        self.year_lbl_2.setFont(font)
        self.year_cmb_2 = QComboBox(self.filters_frame)
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.addItem("")
        self.year_cmb_2.setObjectName(u"year_cmb_2")
        self.year_cmb_2.setGeometry(QRect(430, 8, 70, 25))
        self.year_cmb_2.setStyleSheet(u"background-color: rgb(226, 223, 218);\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Segoe UI\";")
        self.resetfilter_btn = QPushButton(self.filters_frame)
        self.resetfilter_btn.setObjectName(u"resetfilter_btn")
        self.resetfilter_btn.setGeometry(QRect(510, 8, 120, 25))
        self.resetfilter_btn.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.refreshsignals_btn = QPushButton(self.filters_frame)
        self.refreshsignals_btn.setObjectName(u"refreshsignals_btn")
        self.refreshsignals_btn.setGeometry(QRect(650, 8, 120, 25))
        self.refreshsignals_btn.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.time_lbl = QLabel(self.frame_background)
        self.time_lbl.setObjectName(u"time_lbl")
        self.time_lbl.setGeometry(QRect(370, 10, 80, 30))
        palette4 = QPalette()
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush1)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush1)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush1)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush)
        self.time_lbl.setPalette(palette4)
        font1 = QFont()
        font1.setPointSize(17)
        font1.setBold(True)
        self.time_lbl.setFont(font1)
        self.dashboard_frame = QFrame(self.frame_background)
        self.dashboard_frame.setObjectName(u"dashboard_frame")
        self.dashboard_frame.setGeometry(QRect(10, 89, 780, 381))
        self.dashboard_frame.setStyleSheet(u"background-color: rgb(226, 223, 218);")
        self.dashboard_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.dashboard_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.dashboard_table = QTableView(self.dashboard_frame)
        self.dashboard_table.setObjectName(u"dashboard_table")
        self.dashboard_table.setGeometry(QRect(0, 0, 780, 381))
        self.dashboard_table.setStyleSheet(u"color: rgb(0, 0, 0);")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.genre_lbl.setText(QCoreApplication.translate("MainWindow", u"Genre:", None))
        self.year_lbl_1.setText(QCoreApplication.translate("MainWindow", u"Year:", None))
        self.genre_cmb.setItemText(0, QCoreApplication.translate("MainWindow", u"Any", None))
        self.genre_cmb.setItemText(1, QCoreApplication.translate("MainWindow", u"Pop", None))
        self.genre_cmb.setItemText(2, QCoreApplication.translate("MainWindow", u"Country", None))
        self.genre_cmb.setItemText(3, QCoreApplication.translate("MainWindow", u"Rap", None))
        self.genre_cmb.setItemText(4, QCoreApplication.translate("MainWindow", u"Metal", None))

        self.genre_cmb.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Any", None))
        self.year_cmb_1.setItemText(0, QCoreApplication.translate("MainWindow", u"1980", None))
        self.year_cmb_1.setItemText(1, QCoreApplication.translate("MainWindow", u"1981", None))
        self.year_cmb_1.setItemText(2, QCoreApplication.translate("MainWindow", u"1982", None))
        self.year_cmb_1.setItemText(3, QCoreApplication.translate("MainWindow", u"1983", None))
        self.year_cmb_1.setItemText(4, QCoreApplication.translate("MainWindow", u"1984", None))
        self.year_cmb_1.setItemText(5, QCoreApplication.translate("MainWindow", u"1985", None))
        self.year_cmb_1.setItemText(6, QCoreApplication.translate("MainWindow", u"1986", None))
        self.year_cmb_1.setItemText(7, QCoreApplication.translate("MainWindow", u"1987", None))
        self.year_cmb_1.setItemText(8, QCoreApplication.translate("MainWindow", u"1988", None))
        self.year_cmb_1.setItemText(9, QCoreApplication.translate("MainWindow", u"1989", None))
        self.year_cmb_1.setItemText(10, QCoreApplication.translate("MainWindow", u"1990", None))
        self.year_cmb_1.setItemText(11, QCoreApplication.translate("MainWindow", u"1991", None))
        self.year_cmb_1.setItemText(12, QCoreApplication.translate("MainWindow", u"1992", None))
        self.year_cmb_1.setItemText(13, QCoreApplication.translate("MainWindow", u"1993", None))
        self.year_cmb_1.setItemText(14, QCoreApplication.translate("MainWindow", u"1994", None))
        self.year_cmb_1.setItemText(15, QCoreApplication.translate("MainWindow", u"1995", None))
        self.year_cmb_1.setItemText(16, QCoreApplication.translate("MainWindow", u"1996", None))
        self.year_cmb_1.setItemText(17, QCoreApplication.translate("MainWindow", u"1997", None))
        self.year_cmb_1.setItemText(18, QCoreApplication.translate("MainWindow", u"1998", None))
        self.year_cmb_1.setItemText(19, QCoreApplication.translate("MainWindow", u"1999", None))
        self.year_cmb_1.setItemText(20, QCoreApplication.translate("MainWindow", u"2000", None))
        self.year_cmb_1.setItemText(21, QCoreApplication.translate("MainWindow", u"2001", None))
        self.year_cmb_1.setItemText(22, QCoreApplication.translate("MainWindow", u"2002", None))
        self.year_cmb_1.setItemText(23, QCoreApplication.translate("MainWindow", u"2003", None))
        self.year_cmb_1.setItemText(24, QCoreApplication.translate("MainWindow", u"2004", None))
        self.year_cmb_1.setItemText(25, QCoreApplication.translate("MainWindow", u"2005", None))
        self.year_cmb_1.setItemText(26, QCoreApplication.translate("MainWindow", u"2006", None))
        self.year_cmb_1.setItemText(27, QCoreApplication.translate("MainWindow", u"2007", None))
        self.year_cmb_1.setItemText(28, QCoreApplication.translate("MainWindow", u"2008", None))
        self.year_cmb_1.setItemText(29, QCoreApplication.translate("MainWindow", u"2009", None))
        self.year_cmb_1.setItemText(30, QCoreApplication.translate("MainWindow", u"2010", None))
        self.year_cmb_1.setItemText(31, QCoreApplication.translate("MainWindow", u"2011", None))
        self.year_cmb_1.setItemText(32, QCoreApplication.translate("MainWindow", u"2012", None))
        self.year_cmb_1.setItemText(33, QCoreApplication.translate("MainWindow", u"2013", None))
        self.year_cmb_1.setItemText(34, QCoreApplication.translate("MainWindow", u"2014", None))
        self.year_cmb_1.setItemText(35, QCoreApplication.translate("MainWindow", u"2015", None))
        self.year_cmb_1.setItemText(36, QCoreApplication.translate("MainWindow", u"2016", None))
        self.year_cmb_1.setItemText(37, QCoreApplication.translate("MainWindow", u"2017", None))
        self.year_cmb_1.setItemText(38, QCoreApplication.translate("MainWindow", u"2018", None))
        self.year_cmb_1.setItemText(39, QCoreApplication.translate("MainWindow", u"2019", None))
        self.year_cmb_1.setItemText(40, QCoreApplication.translate("MainWindow", u"2020", None))
        self.year_cmb_1.setItemText(41, QCoreApplication.translate("MainWindow", u"2021", None))
        self.year_cmb_1.setItemText(42, QCoreApplication.translate("MainWindow", u"2022", None))
        self.year_cmb_1.setItemText(43, QCoreApplication.translate("MainWindow", u"2023", None))
        self.year_cmb_1.setItemText(44, QCoreApplication.translate("MainWindow", u"2024", None))
        self.year_cmb_1.setItemText(45, QCoreApplication.translate("MainWindow", u"2025", None))
        self.year_cmb_1.setItemText(46, QCoreApplication.translate("MainWindow", u"2026", None))

        self.year_cmb_1.setPlaceholderText(QCoreApplication.translate("MainWindow", u"1980", None))
        self.year_lbl_2.setText(QCoreApplication.translate("MainWindow", u"To", None))
        self.year_cmb_2.setItemText(0, QCoreApplication.translate("MainWindow", u"1980", None))
        self.year_cmb_2.setItemText(1, QCoreApplication.translate("MainWindow", u"1981", None))
        self.year_cmb_2.setItemText(2, QCoreApplication.translate("MainWindow", u"1982", None))
        self.year_cmb_2.setItemText(3, QCoreApplication.translate("MainWindow", u"1983", None))
        self.year_cmb_2.setItemText(4, QCoreApplication.translate("MainWindow", u"1984", None))
        self.year_cmb_2.setItemText(5, QCoreApplication.translate("MainWindow", u"1985", None))
        self.year_cmb_2.setItemText(6, QCoreApplication.translate("MainWindow", u"1986", None))
        self.year_cmb_2.setItemText(7, QCoreApplication.translate("MainWindow", u"1987", None))
        self.year_cmb_2.setItemText(8, QCoreApplication.translate("MainWindow", u"1988", None))
        self.year_cmb_2.setItemText(9, QCoreApplication.translate("MainWindow", u"1989", None))
        self.year_cmb_2.setItemText(10, QCoreApplication.translate("MainWindow", u"1990", None))
        self.year_cmb_2.setItemText(11, QCoreApplication.translate("MainWindow", u"1991", None))
        self.year_cmb_2.setItemText(12, QCoreApplication.translate("MainWindow", u"1992", None))
        self.year_cmb_2.setItemText(13, QCoreApplication.translate("MainWindow", u"1993", None))
        self.year_cmb_2.setItemText(14, QCoreApplication.translate("MainWindow", u"1994", None))
        self.year_cmb_2.setItemText(15, QCoreApplication.translate("MainWindow", u"1995", None))
        self.year_cmb_2.setItemText(16, QCoreApplication.translate("MainWindow", u"1996", None))
        self.year_cmb_2.setItemText(17, QCoreApplication.translate("MainWindow", u"1997", None))
        self.year_cmb_2.setItemText(18, QCoreApplication.translate("MainWindow", u"1998", None))
        self.year_cmb_2.setItemText(19, QCoreApplication.translate("MainWindow", u"1999", None))
        self.year_cmb_2.setItemText(20, QCoreApplication.translate("MainWindow", u"2000", None))
        self.year_cmb_2.setItemText(21, QCoreApplication.translate("MainWindow", u"2001", None))
        self.year_cmb_2.setItemText(22, QCoreApplication.translate("MainWindow", u"2002", None))
        self.year_cmb_2.setItemText(23, QCoreApplication.translate("MainWindow", u"2003", None))
        self.year_cmb_2.setItemText(24, QCoreApplication.translate("MainWindow", u"2004", None))
        self.year_cmb_2.setItemText(25, QCoreApplication.translate("MainWindow", u"2005", None))
        self.year_cmb_2.setItemText(26, QCoreApplication.translate("MainWindow", u"2006", None))
        self.year_cmb_2.setItemText(27, QCoreApplication.translate("MainWindow", u"2007", None))
        self.year_cmb_2.setItemText(28, QCoreApplication.translate("MainWindow", u"2008", None))
        self.year_cmb_2.setItemText(29, QCoreApplication.translate("MainWindow", u"2009", None))
        self.year_cmb_2.setItemText(30, QCoreApplication.translate("MainWindow", u"2010", None))
        self.year_cmb_2.setItemText(31, QCoreApplication.translate("MainWindow", u"2011", None))
        self.year_cmb_2.setItemText(32, QCoreApplication.translate("MainWindow", u"2012", None))
        self.year_cmb_2.setItemText(33, QCoreApplication.translate("MainWindow", u"2013", None))
        self.year_cmb_2.setItemText(34, QCoreApplication.translate("MainWindow", u"2014", None))
        self.year_cmb_2.setItemText(35, QCoreApplication.translate("MainWindow", u"2015", None))
        self.year_cmb_2.setItemText(36, QCoreApplication.translate("MainWindow", u"2016", None))
        self.year_cmb_2.setItemText(37, QCoreApplication.translate("MainWindow", u"2017", None))
        self.year_cmb_2.setItemText(38, QCoreApplication.translate("MainWindow", u"2018", None))
        self.year_cmb_2.setItemText(39, QCoreApplication.translate("MainWindow", u"2019", None))
        self.year_cmb_2.setItemText(40, QCoreApplication.translate("MainWindow", u"2020", None))
        self.year_cmb_2.setItemText(41, QCoreApplication.translate("MainWindow", u"2021", None))
        self.year_cmb_2.setItemText(42, QCoreApplication.translate("MainWindow", u"2022", None))
        self.year_cmb_2.setItemText(43, QCoreApplication.translate("MainWindow", u"2023", None))
        self.year_cmb_2.setItemText(44, QCoreApplication.translate("MainWindow", u"2024", None))
        self.year_cmb_2.setItemText(45, QCoreApplication.translate("MainWindow", u"2025", None))
        self.year_cmb_2.setItemText(46, QCoreApplication.translate("MainWindow", u"2026", None))

        self.year_cmb_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"2026", None))
        self.resetfilter_btn.setText(QCoreApplication.translate("MainWindow", u"Reset Filters", None))
        self.refreshsignals_btn.setText(QCoreApplication.translate("MainWindow", u"Refresh Signals", None))
        self.time_lbl.setText("")
    # retranslateUi

